=== eltntawy/Massenger-Project/Messenger Client Project/bin/com/xml/FirstExampel.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    
    
    <xs:attributeGroup  name="UserGroup">
        <xs:attribute name="userName" type="xs:string"/>
        <xs:attribute name="userID" type="xs:int"/>
    </xs:attributeGroup>
    
    
    <xs:complexType name="MsgBody" >
        <xs:sequence>
            <xs:element name="Text" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="font" type="xs:string"/>
        <xs:attribute name="size" type="xs:int"/>
        <xs:attribute name="Color" type="xs:string"/>
    </xs:complexType>
    
    <xs:complexType name="UserTo">
        <xs:sequence>
            <xs:element name="Body" type="MsgBody"/>
        </xs:sequence>
        <xs:attributeGroup ref="UserGroup"/>
    </xs:complexType>
    
    <xs:complexType name="Login">
        <xs:sequence>
            <xs:element name="UserTo" type="UserTo" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="UserGroup" />
    </xs:complexType>
 
    
    <xs:element name="MessageHistory">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Login" type="Login" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="msgTime" type="xs:time"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== eltntawy/Massenger-Project/Messenger Client Project/bin/com/xml/XMLMessenger.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<MessageHistory
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='FirstExampel.xsd'>
    <Login userName="" userID="">
        <UserTo userName="" userID="">
            <Body font="" size="" Color="">
                <Text></Text>
            </Body>
        </UserTo>
        <UserTo userName="" userID="">
            <Body font="" size="" Color="">
                <Text></Text>
            </Body>
        </UserTo>
        <UserTo userName="" userID="">
            <Body font="" size="" Color="">
                <Text></Text>
            </Body>
        </UserTo>
    </Login>
    <Login userName="" userID="">
        <UserTo userName="" userID="">
            <Body font="" size="" Color="">
                <Text></Text>
            </Body>
        </UserTo>
    </Login>
    <Login userName="" userID="">
        <UserTo userName="" userID="">
            <Body font="" size="" Color="">
                <Text></Text>
            </Body>
        </UserTo>
    </Login>

</MessageHistory>

=== eltntawy/Massenger-Project/Messenger Client Project/src/com/xml/newXMLDocument2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<MessageHistory
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='FirstExampel.xsd'>
    <Login userName="aya" userID="20">
        <UserTo userName="aya" userID="25">
            <Body>
                <Text>Okay</Text>
            </Body>
        </UserTo>
    </Login>
    <Login userName="aya" userID="1">
        <UserTo userName="marwa" userID="1">
            <Body>
                <Text>Heeey</Text>
                <Text>Heeey</Text>
            </Body>
        </UserTo>
    </Login>

</MessageHistory>

=== eltntawy/Massenger-Project/Messenger Client Project/src/com/xml/XMLMessenger.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type="text/xsl" href="Messenger_StyleSheet.xsl" ?>
<MessageHistory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src\com.xml\FirstExampel.xsd">
    <Login userName="aya" userID="20">
        <UserTo userName="aya" userID="25">
            <Body>
                <Text>Okay</Text>
            </Body>
        </UserTo>
    </Login>
    <Login userName="aya" userID="1">
        <UserTo userName="marwa" userID="1">
            <Body>
                <Text>Heeey</Text>
            </Body>
        </UserTo>
    </Login>
    <Login userName="aya" userID="30">
        <UserTo userName="marwa" userID="20">
            <Body>
                <Text>Heeey</Text>
                <Text>Heeey</Text>
            </Body>
        </UserTo>
    </Login>
</MessageHistory>
